import { hashSync } from 'bcrypt-ts-edge'
const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'jane@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Neon Cyberpunk MagSafe Case',
      slug: 'neon-cyberpunk-magsafe-case',
      category: 'Phone Cases',
      description: 'Futuristic aesthetic with military-grade drop protection',
      images: ['/images/cases/c1.jpeg', '/images/cases/c11.jpeg'],
      price: 59.99,
      brand: 'UrbanTech',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Minimalist Matte Black Slim Case',
      slug: 'minimalist-matte-black-slim-case',
      category: 'Phone Cases',
      description: 'Ultra-thin design that preserves the original feel of your phone',
      images: ['/images/cases/c2.jpeg', '/images/cases/c22.jpeg'],
      price: 29.99,
      brand: 'MonoGuard',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Crystal Clear Anti-Yellowing Case',
      slug: 'crystal-clear-anti-yellowing-case',
      category: 'Phone Cases',
      description: 'Show off your phone color with our high-clarity material',
      images: ['/images/cases/c3.jpeg', '/images/cases/c33.jpeg'],
      price: 24.95,
      brand: 'ClearView',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Luxury Leather Wallet Case',
      slug: 'luxury-leather-wallet-case',
      category: 'Phone Cases',
      description: 'Premium genuine leather with built-in card slots',
      images: ['/images/cases/c4.jpeg', '/images/cases/c44.jpeg'],
      price: 64.95,
      brand: 'LuxeCover',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Abstract Geometric Marble Case',
      slug: 'abstract-geometric-marble-case',
      category: 'Phone Cases',
      description: 'Artistic marble patterns with gold foil accents',
      images: ['/images/cases/c5.jpeg', '/images/cases/c55.jpeg'],
      price: 34.99,
      brand: 'ArtCase',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Heavy Duty Rugged Armor Case',
      slug: 'heavy-duty-rugged-armor-case',
      category: 'Phone Cases',
      description: 'Dual-layer protection for extreme outdoor activities',
      images: ['/images/cases/c6.jpeg', '/images/cases/c66.jpeg'],
      price: 45.99,
      brand: 'IronShield',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
}

export default sampleData
